version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - RIOT_API_KEY=RGAPI-1d749fc0-5f3d-447f-98de-4f1a81f5197c
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge